import { randomUUIDv7 } from "bun";
import { type Transaction } from "..";
import { testQuestion } from "../schema";

type TestQuestion = typeof testQuestion.$inferInsert;

// Generate data function to create fresh UUIDs on each seed
function generateData(): TestQuestion[] {
  return [
    // Test 4 Questions (12 questions)
    {
      id: randomUUIDv7(),
      text: "Cara saya agar lebih mudah memahami materi kuliah adalah dengan…",
      type: "single_choice",
      order: 0,
      testId: 4,
    },
    {
      id: randomUUIDv7(),
      text: "Jenis tugas kuliah yang menarik minat saya & membuat bersemangat mengerjakannya adalah…",
      type: "single_choice",
      order: 1,
      testId: 4,
    },
    {
      id: randomUUIDv7(),
      text: "Saat kerja kelompok, peran / bagian yang paling saya nikmati adalah…",
      type: "single_choice",
      order: 2,
      testId: 4,
    },
    {
      id: randomUUIDv7(),
      text: "Saya suka teman belajar yang …",
      type: "single_choice",
      order: 3,
      testId: 4,
    },
    {
      id: randomUUIDv7(),
      text: "Saat diminta membuat kelompok, saya akan memilih teman kelompok yang …",
      type: "single_choice",
      order: 4,
      testId: 4,
    },
    {
      id: randomUUIDv7(),
      text: "Peran yang paling saya nikmati saat presentasi adalah …",
      type: "single_choice",
      order: 5,
      testId: 4,
    },
    {
      id: randomUUIDv7(),
      text: "Saat kelompok saya menghadapi kesulitan dalam mengerjakan tugas, yang biasanya saya lakukan…",
      type: "single_choice",
      order: 6,
      testId: 4,
    },
    {
      id: randomUUIDv7(),
      text: "Saat membantu teman yang kesulitan belajar, saya biasanya…",
      type: "single_choice",
      order: 7,
      testId: 4,
    },
    {
      id: randomUUIDv7(),
      text: "Saya tertarik untuk mengikuti kelas dengan karakteristik mengajar dosen yang …",
      type: "single_choice",
      order: 8,
      testId: 4,
    },
    {
      id: randomUUIDv7(),
      text: "Kegiatan mahasiswa yang menarik minat saya …",
      type: "single_choice",
      order: 9,
      testId: 4,
    },
    {
      id: randomUUIDv7(),
      text: "Saat punya waktu luang, saya lebih suka…",
      type: "single_choice",
      order: 10,
      testId: 4,
    },
    {
      id: randomUUIDv7(),
      text: "Dalam 5 tahun ke depan, saya membayangkan akan menekuni jenis profesi …",
      type: "single_choice",
      order: 11,
      testId: 4,
    },
    // Test 5 Questions (28 questions)
    {
      id: randomUUIDv7(),
      text: "Ide akan lebih mudah datang jika:",
      type: "single_choice",
      order: 0,
      testId: 5,
    },
    {
      id: randomUUIDv7(),
      text: "Belajar akan lebih efektif di tempat yang suasananya:",
      type: "single_choice",
      order: 1,
      testId: 5,
    },
    {
      id: randomUUIDv7(),
      text: "Lebih bersemangat belajar di kelas yang suasananya:",
      type: "single_choice",
      order: 2,
      testId: 5,
    },
    {
      id: randomUUIDv7(),
      text: "Lebih mudah memahami materi pelajaran jika:",
      type: "single_choice",
      order: 3,
      testId: 5,
    },
    {
      id: randomUUIDv7(),
      text: "Lebih enak mengulang pelajaran dengan cara:",
      type: "single_choice",
      order: 4,
      testId: 5,
    },
    {
      id: randomUUIDv7(),
      text: "Lebih bersemangat jika mengerjakan tugas:",
      type: "single_choice",
      order: 5,
      testId: 5,
    },
    {
      id: randomUUIDv7(),
      text: "Waktu kosong terasa lebih menyenangkan jika digunakan untuk:",
      type: "single_choice",
      order: 6,
      testId: 5,
    },
    {
      id: randomUUIDv7(),
      text: "Cara saya mempersiapkan bahan presentasi:",
      type: "single_choice",
      order: 7,
      testId: 5,
    },
    {
      id: randomUUIDv7(),
      text: "Cara saya mencatat penjelasan dosen:",
      type: "single_choice",
      order: 8,
      testId: 5,
    },
    {
      id: randomUUIDv7(),
      text: "Belajar akan lebih seru jika:",
      type: "single_choice",
      order: 9,
      testId: 5,
    },
    {
      id: randomUUIDv7(),
      text: "Kontribusi saya dalam tugas kelompok biasanya:",
      type: "single_choice",
      order: 10,
      testId: 5,
    },
    {
      id: randomUUIDv7(),
      text: "Saat membuat catatan mandiri, saya lebih sering:",
      type: "single_choice",
      order: 11,
      testId: 5,
    },
    {
      id: randomUUIDv7(),
      text: "Topik diskusi yang membuat saya bersemangat:",
      type: "single_choice",
      order: 12,
      testId: 5,
    },
    {
      id: randomUUIDv7(),
      text: "Materi kuliah akan lebih mudah saya pahami jika:",
      type: "single_choice",
      order: 13,
      testId: 5,
    },
    {
      id: randomUUIDv7(),
      text: "Jika terdapat perbedaan pendapat saat berdiskusi, saya lebih memilih:",
      type: "single_choice",
      order: 14,
      testId: 5,
    },
    {
      id: randomUUIDv7(),
      text: "Jika diminta untuk menilai presentasi kelompok lain, saya lebih memperhatikan:",
      type: "single_choice",
      order: 15,
      testId: 5,
    },
    {
      id: randomUUIDv7(),
      text: "Menurut saya bantuan terbaik untuk teman yang sulit memahami pelajaran adalah:",
      type: "single_choice",
      order: 16,
      testId: 5,
    },
    {
      id: randomUUIDv7(),
      text: "Jika dalam kelompok ada teman yang kurang berkontribusi, yang akan saya lakukan:",
      type: "single_choice",
      order: 17,
      testId: 5,
    },
    {
      id: randomUUIDv7(),
      text: "Dalam kelompok belajar, yang paling penting buat saya:",
      type: "single_choice",
      order: 18,
      testId: 5,
    },
    {
      id: randomUUIDv7(),
      text: "Dalam memilih teman dekat, saya lebih tertarik pada:",
      type: "single_choice",
      order: 19,
      testId: 5,
    },
    {
      id: randomUUIDv7(),
      text: "Saat teman curhat, saya akan:",
      type: "single_choice",
      order: 20,
      testId: 5,
    },
    {
      id: randomUUIDv7(),
      text: "Pola saya menulis makalah:",
      type: "single_choice",
      order: 21,
      testId: 5,
    },
    {
      id: randomUUIDv7(),
      text: "Jika ada beberapa tugas dalam waktu bersamaan, saya biasanya:",
      type: "single_choice",
      order: 22,
      testId: 5,
    },
    {
      id: randomUUIDv7(),
      text: "Dalam mengatur kegiatan sehari-hari, saya lebih suka:",
      type: "single_choice",
      order: 23,
      testId: 5,
    },
    {
      id: randomUUIDv7(),
      text: "Saya lebih suka alur diskusi yang:",
      type: "single_choice",
      order: 24,
      testId: 5,
    },
    {
      id: randomUUIDv7(),
      text: "Saat ada janjian mengerjakan tugas kelompok:",
      type: "single_choice",
      order: 25,
      testId: 5,
    },
    {
      id: randomUUIDv7(),
      text: "Cara saya mempersiapkan diri saat menjadi presenter:",
      type: "single_choice",
      order: 26,
      testId: 5,
    },
    {
      id: randomUUIDv7(),
      text: "Saat mengulang membaca materi kuliah:",
      type: "single_choice",
      order: 27,
      testId: 5,
    },
    // Test 6 Questions (36 questions)
    {
      id: randomUUIDv7(),
      text: "Secara umum, saya merasa puas dengan kualitas diri saya saat ini",
      type: "likert",
      order: 0,
      testId: 6,
    },
    {
      id: randomUUIDv7(),
      text: "Saya sering menginginkan kehidupan seperti orang yang terlihat lebih beruntung",
      type: "likert",
      order: 1,
      testId: 6,
    },
    {
      id: randomUUIDv7(),
      text: "Saya mampu menerima kekurangan saya tanpa harus membenci diri sendiri",
      type: "likert",
      order: 2,
      testId: 6,
    },
    {
      id: randomUUIDv7(),
      text: "Ada hal-hal dalam diri saya yang membuat saya terus merasa insecure (rendah diri)",
      type: "likert",
      order: 3,
      testId: 6,
    },
    {
      id: randomUUIDv7(),
      text: "Saya sudah mampu berdamai dengan hampir semua pengalaman buruk di masa lalu",
      type: "likert",
      order: 4,
      testId: 6,
    },
    {
      id: randomUUIDv7(),
      text: "Masih banyak kejadian di masa lalu yang ingin saya ubah karena membuat saya kecewa saat mengingatnya",
      type: "likert",
      order: 5,
      testId: 6,
    },
    {
      id: randomUUIDv7(),
      text: "Saya punya cara sendiri dalam menentukan apa yang penting bagi hidup saya",
      type: "likert",
      order: 6,
      testId: 6,
    },
    {
      id: randomUUIDv7(),
      text: "Saya gampang overthinking (berpikir berlebihan) setelah mendapat penilaian negatif dari orang lain",
      type: "likert",
      order: 7,
      testId: 6,
    },
    {
      id: randomUUIDv7(),
      text: "Saya berani memilih keputusan meski berbeda dari kebanyakan orang",
      type: "likert",
      order: 8,
      testId: 6,
    },
    {
      id: randomUUIDv7(),
      text: "Seringkali saya mengikuti apa kata orang meskipun tidak sesuai dengan keinginan saya",
      type: "likert",
      order: 9,
      testId: 6,
    },
    {
      id: randomUUIDv7(),
      text: "Saya akan tetap berkata jujur meskipun tidak sesuai dengan harapan orang lain",
      type: "likert",
      order: 10,
      testId: 6,
    },
    {
      id: randomUUIDv7(),
      text: "Seringkali saya menyesuaikan perilaku agar bisa diterima di lingkungan sosial",
      type: "likert",
      order: 11,
      testId: 6,
    },
    {
      id: randomUUIDv7(),
      text: "Saya sudah memiliki rencana dengan langkah yang jelas untuk mencapai cita-cita di masa depan",
      type: "likert",
      order: 12,
      testId: 6,
    },
    {
      id: randomUUIDv7(),
      text: "Saat ini saya tidak tahu dengan pasti apa yang ingin saya capai di masa depan",
      type: "likert",
      order: 13,
      testId: 6,
    },
    {
      id: randomUUIDv7(),
      text: "Saya berani memilih keputusan meski berbeda dari kebanyakan orang",
      type: "likert",
      order: 14,
      testId: 6,
    },
    {
      id: randomUUIDv7(),
      text: "Rasanya tidak banyak momen berharga dari perjalanan hidup yang telah saya lalui",
      type: "likert",
      order: 15,
      testId: 6,
    },
    {
      id: randomUUIDv7(),
      text: "Optimis dan yakin, bahwa di masa depan saya akan menjadi pribadi yang berguna bagi banyak orang",
      type: "likert",
      order: 16,
      testId: 6,
    },
    {
      id: randomUUIDv7(),
      text: "Jika melihat kondisi diri saat ini, rasanya di masa depan saya akan kesulitan untuk bisa sukses",
      type: "likert",
      order: 17,
      testId: 6,
    },
    {
      id: randomUUIDv7(),
      text: "Saya merasakan banyak perubahan positif pada diri saya dalam 1 tahun terakhir",
      type: "likert",
      order: 18,
      testId: 6,
    },
    {
      id: randomUUIDv7(),
      text: "Beberapa kebiasaan buruk masih menghambat saya untuk berkembang",
      type: "likert",
      order: 19,
      testId: 6,
    },
    {
      id: randomUUIDv7(),
      text: "Saya rutin melakukan evaluasi & refleksi diri, untuk semakin memahami bakat serta potensi yang dimiliki",
      type: "likert",
      order: 20,
      testId: 6,
    },
    {
      id: randomUUIDv7(),
      text: "Saya belum menyadari apa saja potensi diri yang perlu saya kembangkan",
      type: "likert",
      order: 21,
      testId: 6,
    },
    {
      id: randomUUIDv7(),
      text: "Saya senang mencari tantangan dengan mencoba berbagai pengalaman baru",
      type: "likert",
      order: 22,
      testId: 6,
    },
    {
      id: randomUUIDv7(),
      text: "Seringkali saya menghindar untuk mencoba hal-hal baru, karena takut gagal",
      type: "likert",
      order: 23,
      testId: 6,
    },
    {
      id: randomUUIDv7(),
      text: "Saya mampu menata lingkungan agar memberikan suasana yang kondusif untuk saya belajar",
      type: "likert",
      order: 24,
      testId: 6,
    },
    {
      id: randomUUIDv7(),
      text: "Seringkali saya merasa kewalahan untuk menghadapi tuntutan lingkungan kepada saya",
      type: "likert",
      order: 25,
      testId: 6,
    },
    {
      id: randomUUIDv7(),
      text: "Saya mampu menyelesaikan semua tanggung jawab sehari-hari tanpa merasa kewalahan",
      type: "likert",
      order: 26,
      testId: 6,
    },
    {
      id: randomUUIDv7(),
      text: "Seringkali saya merasa memiliki terlalu banyak kegiatan, sehingga sulit mengaturnya",
      type: "likert",
      order: 27,
      testId: 6,
    },
    {
      id: randomUUIDv7(),
      text: "Saya termasuk orang yang jeli menemukan peluang dan kesempatan yang ada di sekitar",
      type: "likert",
      order: 28,
      testId: 6,
    },
    {
      id: randomUUIDv7(),
      text: "Seringkali saya terlambat menyadari jika ternyata di sekitar saya terdapat banyak kesempatan & peluang baik",
      type: "likert",
      order: 29,
      testId: 6,
    },
    {
      id: randomUUIDv7(),
      text: "Saya memiliki beberapa teman yang benar-benar dipercaya untuk menyimpan rahasia",
      type: "likert",
      order: 30,
      testId: 6,
    },
    {
      id: randomUUIDv7(),
      text: "Rasanya orang-orang di sekitar saya tidak benar-benar bisa memahami saya",
      type: "likert",
      order: 31,
      testId: 6,
    },
    {
      id: randomUUIDv7(),
      text: "Saya merasa mampu dan nyaman untuk menunjukkan perhatian secara langsung kepada orang lain",
      type: "likert",
      order: 32,
      testId: 6,
    },
    {
      id: randomUUIDv7(),
      text: "Seringkali saya menjadi orang yang diabaikan di lingkaran pertemanan",
      type: "likert",
      order: 33,
      testId: 6,
    },
    {
      id: randomUUIDv7(),
      text: "Mudah bagi saya untuk meredam ego dan mengalah agar perdebatan tidak berlarut-larut",
      type: "likert",
      order: 34,
      testId: 6,
    },
    {
      id: randomUUIDv7(),
      text: "Seringkali kesabaran saya berkurang saat menghadapi orang yang pemikirannya tidak sejalan dengan saya",
      type: "likert",
      order: 35,
      testId: 6,
    },
  ];
}

export const data: TestQuestion[] = generateData();

export default async function seed(tx: Transaction) {
  await tx.insert(testQuestion).values(data);
}
